com:
  zipkin:
    serviceName: LOGIN-GATEWAY
    url:  http://127.0.0.1:9411/api/v2/spans
    connectTimeout: 10000
    readTimeout: 1000
    flushInterval: 1000
    compressionEnabled: true
    endpoint: http://127.0.0.1:9411/api/v2/spans

# 端口信息
server:
  port: 5001
# 应用名称
spring:
  application:
    name: LOGIN-GATEWAY
  profiles:
    active: dev
# 日志级别
logging:
  level:
    key : info
  config: classpath:logback-spring.xml

eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka-server-01:7001/eureka/
zuul:
  routes:
    login:
      path: /api/login/**
      serviceId: LOGIN-SERVICE
      stripPrefix: false
    register:
      path: /api/register/**
      serviceId: REGISTER-SERVICE
      stripPrefix: false
    user:
      path: /user/center/**
      serviceId: USER-SERVICE
      stripPrefix: false

