com: 
  zipkin:
    serviceName: REGISTER-SERVICE
    url:  http://127.0.0.1:9411/api/v2/spans
    connectTimeout: 10000
    readTimeout: 1000
    flushInterval: 1000
    compressionEnabled: true
    endpoint: http://127.0.0.1:9411/api/v2/spans


# 端口信息
server:
  port: 9001
# 应用名称
spring:
  application:
    name: REGISTER-SERVICE
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123
    driverClassName: com.mysql.jdbc.Driver
    
# 日志级别
logging:
  level:
    key : info
  config: classpath:logback-spring.xml


eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka-server-01:7001/eureka/
