spring:
  profiles:
    active: server1

server:
  port: 7001
  display-name: eureka-server-01
  address: 127.0.0.1

eureka:
  instance:
    hostname: eureka-server-01
    appname: eureka-server
    lease-renewal-interval-in-seconds: 10     # 定义服务续约任务的调用间隔时间，默认是30秒
    lease-expiration-duration-in-seconds: 20  # 定义服务失效的时间，默认是是90秒
  client:
    register-with-eureka: false  #由于应用为注册中心，所以设置为false，代表不向注册中心注册自己。
    fetch-registry: false #由于注册中心的指责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url:
      defaultZone : http://eureka-server-01:7001/eureka/
