# 端口信息
server:
  port: 9002
# 应用名称
spring:
  application:
    name: REGISTER-SERVICE
  profiles:
    active: test
# 数据库的连接信息
# 日志级别
logging:
  level:
    key : info
  config: classpath:logback-spring.xml


eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka-server-03:7003/eureka/
